steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes.git']
- id: 'Create cluster'
  entrypoint: 'bash'
  args:
  - 'cd continuous-deployment-on-kubernetes'
  - >
    gcloud container clusters create cicd-infra \
    --machine-type n1-standard-2 --num-nodes 2 \
    --scopes "https://www.googleapis.com/auth/projecthosting,cloud-platform"
